// B2 Level Words (150 needed)
const fs = require('fs');
const VocabularyManager = require('./vocabulary-utils.js');

const vm = new VocabularyManager();

const b2Words = [
    // Business & Economics (30 words)
    { word: "economy", pos: "n.", thai: "เศรษฐกิจ", definition: "system of money and trade", hint: "financial system", cats: ["work"], examples: [{ en: "The economy is growing.", th: "เศรษฐกิจกำลังเติบโต" }] },
    { word: "investment", pos: "n.", thai: "การลงทุน", definition: "money put into business", hint: "business funding", cats: ["work", "money"], examples: [{ en: "Investment requires research.", th: "การลงทุนต้องใช้การวิจัย" }] },
    { word: "profit", pos: "n.", thai: "กำไร", definition: "money gained from business", hint: "business earnings", cats: ["work", "money"], examples: [{ en: "The company made profit.", th: "บริษัททำกำไรได้" }] },
    { word: "budget", pos: "n.", thai: "งบประมาณ", definition: "plan for spending money", hint: "money plan", cats: ["work", "money"], examples: [{ en: "We need to plan our budget.", th: "เราต้องวางแผนงบประมาณ" }] },
    { word: "marketing", pos: "n.", thai: "การตลาด", definition: "promoting products", hint: "selling strategy", cats: ["work"], examples: [{ en: "Marketing increases sales.", th: "การตลาดเพิ่มยอดขาย" }] },
    { word: "revenue", pos: "n.", thai: "รายได้", definition: "income from business", hint: "business income", cats: ["work", "money"], examples: [{ en: "Revenue increased this quarter.", th: "รายได้เพิ่มขึ้นในไตรมาสนี้" }] },
    { word: "expense", pos: "n.", thai: "ค่าใช้จ่าย", definition: "money spent", hint: "spending cost", cats: ["work", "money"], examples: [{ en: "Control business expenses.", th: "ควบคุมค่าใช้จ่ายธุรกิจ" }] },
    { word: "competition", pos: "n.", thai: "การแข่งขัน", definition: "rivalry in business", hint: "business rivalry", cats: ["work"], examples: [{ en: "Competition drives innovation.", th: "การแข่งขันขับเคลื่อนนวัตกรรม" }] },
    { word: "market", pos: "n.", thai: "ตลาด", definition: "place for buying and selling", hint: "trade place", cats: ["work"], examples: [{ en: "The market is competitive.", th: "ตลาดมีการแข่งขัน" }] },
    { word: "customer", pos: "n.", thai: "ลูกค้า", definition: "person who buys", hint: "buyer", cats: ["work"], examples: [{ en: "Customer satisfaction is key.", th: "ความพึงพอใจของลูกค้าเป็นกุญแจ" }] },
    { word: "supplier", pos: "n.", thai: "ผู้จัดหา", definition: "person who provides goods", hint: "goods provider", cats: ["work"], examples: [{ en: "Find reliable suppliers.", th: "หาผู้จัดหาที่เชื่อถือได้" }] },
    { word: "partnership", pos: "n.", thai: "ความเป็นหุ้นส่วน", definition: "business cooperation", hint: "business alliance", cats: ["work"], examples: [{ en: "Partnership benefits both companies.", th: "ความเป็นหุ้นส่วนเป็นประโยชน์ต่อทั้งสองบริษัท" }] },
    { word: "negotiation", pos: "n.", thai: "การเจรจา", definition: "discussion to reach agreement", hint: "deal discussion", cats: ["work"], examples: [{ en: "Negotiation skills are valuable.", th: "ทักษะการเจรจามีค่า" }] },
    { word: "contract", pos: "n.", thai: "สัญญา", definition: "legal business agreement", hint: "legal deal", cats: ["work"], examples: [{ en: "Review the contract carefully.", th: "ตรวจสอบสัญญาอย่างระมัดระวัง" }] },
    { word: "proposal", pos: "n.", thai: "ข้อเสนอ", definition: "suggested plan", hint: "suggested idea", cats: ["work"], examples: [{ en: "Submit your proposal by Friday.", th: "ส่งข้อเสนอภายในวันศุกร์" }] },
    { word: "analysis", pos: "n.", thai: "การวิเคราะห์", definition: "detailed examination", hint: "detailed study", cats: ["work"], examples: [{ en: "Market analysis shows trends.", th: "การวิเคราะห์ตลาดแสดงแนวโน้ม" }] },
    { word: "strategy", pos: "n.", thai: "กลยุทธ์", definition: "long-term plan", hint: "master plan", cats: ["work"], examples: [{ en: "Develop a marketing strategy.", th: "พัฒนากลยุทธ์การตลาด" }] },
    { word: "efficiency", pos: "n.", thai: "ประสิทธิภาพ", definition: "doing things well", hint: "good performance", cats: ["work"], examples: [{ en: "Improve work efficiency.", th: "เพิ่มประสิทธิภาพการทำงาน" }] },
    { word: "productivity", pos: "n.", thai: "ผลผลิต", definition: "rate of output", hint: "work output", cats: ["work"], examples: [{ en: "Technology increases productivity.", th: "เทคโนโลยีเพิ่มผลผลิต" }] },
    { word: "innovation", pos: "n.", thai: "นวัตกรรม", definition: "new ideas or methods", hint: "new creation", cats: ["work"], examples: [{ en: "Innovation drives success.", th: "นวัตกรรมขับเคลื่อนความสำเร็จ" }] },
    { word: "entrepreneur", pos: "n.", thai: "ผู้ประกอบการ", definition: "person who starts business", hint: "business starter", cats: ["work"], examples: [{ en: "Entrepreneurs take risks.", th: "ผู้ประกอบการเสี่ยงภัย" }] },
    { word: "corporation", pos: "n.", thai: "บริษัทมหาชน", definition: "large business company", hint: "big company", cats: ["work"], examples: [{ en: "The corporation has many employees.", th: "บริษัทมหาชนมีพนักงานมาก" }] },
    { word: "industry", pos: "n.", thai: "อุตสาหกรรม", definition: "business sector", hint: "business field", cats: ["work"], examples: [{ en: "The tech industry is growing.", th: "อุตสาหกรรมเทคโนโลยีกำลังเติบโต" }] },
    { word: "manufacturing", pos: "n.", thai: "การผลิต", definition: "making products", hint: "product making", cats: ["work"], examples: [{ en: "Manufacturing requires machinery.", th: "การผลิตต้องใช้เครื่องจักร" }] },
    { word: "distribution", pos: "n.", thai: "การจัดจำหน่าย", definition: "delivering products", hint: "product delivery", cats: ["work"], examples: [{ en: "Distribution network is important.", th: "เครือข่ายการจัดจำหน่ายสำคัญ" }] },
    { word: "retail", pos: "n.", thai: "การค้าปลีก", definition: "selling to consumers", hint: "direct selling", cats: ["work"], examples: [{ en: "Retail stores serve customers.", th: "ร้านค้าปลีกให้บริการลูกค้า" }] },
    { word: "wholesale", pos: "n.", thai: "การค้าส่ง", definition: "selling in large quantities", hint: "bulk selling", cats: ["work"], examples: [{ en: "Wholesale prices are lower.", th: "ราคาค้าส่งต่ำกว่า" }] },
    { word: "franchise", pos: "n.", thai: "แฟรนไชส์", definition: "business licensing system", hint: "business license", cats: ["work"], examples: [{ en: "Buy a restaurant franchise.", th: "ซื้อแฟรนไชส์ร้านอาหาร" }] },
    { word: "merger", pos: "n.", thai: "การควบรวม", definition: "combining companies", hint: "company joining", cats: ["work"], examples: [{ en: "The merger created a giant company.", th: "การควบรวมสร้างบริษัทยักษ์" }] },
    { word: "acquisition", pos: "n.", thai: "การซื้อกิจการ", definition: "buying another company", hint: "company purchase", cats: ["work"], examples: [{ en: "The acquisition was successful.", th: "การซื้อกิจการสำเร็จ" }] },

    // Science & Technology (30 words)
    { word: "research", pos: "n.", thai: "การวิจัย", definition: "systematic investigation", hint: "scientific study", cats: ["school", "work"], examples: [{ en: "Research takes time.", th: "การวิจัยใช้เวลา" }] },
    { word: "experiment", pos: "n.", thai: "การทดลอง", definition: "scientific test", hint: "lab test", cats: ["school"], examples: [{ en: "The experiment was successful.", th: "การทดลองสำเร็จ" }] },
    { word: "theory", pos: "n.", thai: "ทฤษฎี", definition: "explanation of phenomena", hint: "scientific idea", cats: ["school"], examples: [{ en: "Einstein's theory is famous.", th: "ทฤษฎีของไอน์สไตน์มีชื่อเสียง" }] },
    { word: "discovery", pos: "n.", thai: "การค้นพบ", definition: "finding something new", hint: "new finding", cats: ["school"], examples: [{ en: "The discovery changed science.", th: "การค้นพบเปลี่ยนวิทยาศาสตร์" }] },
    { word: "invention", pos: "n.", thai: "การประดิษฐ์", definition: "creating something new", hint: "new creation", cats: ["school", "technology"], examples: [{ en: "The invention helps people.", th: "การประดิษฐ์ช่วยเหลือผู้คน" }] },
    { word: "laboratory", pos: "n.", thai: "ห้องปฏิบัติการ", definition: "place for scientific work", hint: "science room", cats: ["school"], examples: [{ en: "Work in the laboratory.", th: "ทำงานในห้องปฏิบัติการ" }] },
    { word: "hypothesis", pos: "n.", thai: "สมมติฐาน", definition: "proposed explanation", hint: "scientific guess", cats: ["school"], examples: [{ en: "Test your hypothesis.", th: "ทดสอบสมมติฐานของคุณ" }] },
    { word: "evidence", pos: "n.", thai: "หลักฐาน", definition: "proof supporting theory", hint: "supporting proof", cats: ["school"], examples: [{ en: "Evidence supports the theory.", th: "หลักฐานสนับสนุนทฤษฎี" }] },
    { word: "conclusion", pos: "n.", thai: "บทสรุป", definition: "final result", hint: "final answer", cats: ["school"], examples: [{ en: "Draw a conclusion from data.", th: "สรุปผลจากข้อมูล" }] },
    { word: "methodology", pos: "n.", thai: "วิธีการ", definition: "system of methods", hint: "way of doing", cats: ["school"], examples: [{ en: "Use proper methodology.", th: "ใช้วิธีการที่เหมาะสม" }] },
    { word: "data", pos: "n.", thai: "ข้อมูล", definition: "facts and statistics", hint: "information facts", cats: ["school", "technology"], examples: [{ en: "Analyze the data carefully.", th: "วิเคราะห์ข้อมูลอย่างระมัดระวัง" }] },
    { word: "statistics", pos: "n.", thai: "สถิติ", definition: "numerical data", hint: "number facts", cats: ["school"], examples: [{ en: "Statistics show the trend.", th: "สถิติแสดงแนวโน้ม" }] },
    { word: "variable", pos: "n.", thai: "ตัวแปร", definition: "changeable factor", hint: "changing element", cats: ["school"], examples: [{ en: "Control the variables.", th: "ควบคุมตัวแปร" }] },
    { word: "formula", pos: "n.", thai: "สูตร", definition: "mathematical expression", hint: "math rule", cats: ["school"], examples: [{ en: "Use the correct formula.", th: "ใช้สูตรที่ถูกต้อง" }] },
    { word: "equation", pos: "n.", thai: "สมการ", definition: "mathematical statement", hint: "math equality", cats: ["school"], examples: [{ en: "Solve the equation.", th: "แก้สมการ" }] },
    { word: "algorithm", pos: "n.", thai: "อัลกอริทึม", definition: "step-by-step procedure", hint: "step process", cats: ["technology"], examples: [{ en: "The algorithm is efficient.", th: "อัลกอริทึมมีประสิทธิภาพ" }] },
    { word: "artificial", pos: "adj.", thai: "เทียม", definition: "made by humans", hint: "not natural", cats: ["technology"], examples: [{ en: "Artificial intelligence is advancing.", th: "ปัญญาเทียมกำลังก้าวหน้า" }] },
    { word: "intelligence", pos: "n.", thai: "ปัญญา", definition: "ability to learn and understand", hint: "smart thinking", cats: ["technology"], examples: [{ en: "Human intelligence is complex.", th: "ปัญญาของมนุษย์ซับซ้อน" }] },
    { word: "automation", pos: "n.", thai: "ระบบอัตโนมัติ", definition: "automatic operation", hint: "self-operating", cats: ["technology"], examples: [{ en: "Automation improves efficiency.", th: "ระบบอัตโนมัติเพิ่มประสิทธิภาพ" }] },
    { word: "robotics", pos: "n.", thai: "หุ่นยนต์", definition: "robot technology", hint: "robot science", cats: ["technology"], examples: [{ en: "Robotics is the future.", th: "หุ่นยนต์คืออนาคต" }] },
    { word: "biotechnology", pos: "n.", thai: "เทคโนโลยีชีวภาพ", definition: "technology using living organisms", hint: "bio-tech", cats: ["technology"], examples: [{ en: "Biotechnology helps medicine.", th: "เทคโนโลยีชีวภาพช่วยการแพทย์" }] },
    { word: "nanotechnology", pos: "n.", thai: "นาโนเทคโนโลยี", definition: "technology at molecular level", hint: "tiny tech", cats: ["technology"], examples: [{ en: "Nanotechnology has many applications.", th: "นาโนเทคโนโลยีมีการใช้งานมาก" }] },
    { word: "genetics", pos: "n.", thai: "พันธุศาสตร์", definition: "study of heredity", hint: "gene study", cats: ["school"], examples: [{ en: "Genetics explains inheritance.", th: "พันธุศาสตร์อธิบายการถ่ายทอด" }] },
    { word: "evolution", pos: "n.", thai: "วิวัฒนาการ", definition: "gradual development", hint: "gradual change", cats: ["school"], examples: [{ en: "Evolution takes millions of years.", th: "วิวัฒนาการใช้เวลาหลายล้านปี" }] },
    { word: "ecosystem", pos: "n.", thai: "ระบบนิเวศ", definition: "biological community", hint: "nature system", cats: ["nature"], examples: [{ en: "Protect the ecosystem.", th: "ปกป้องระบบนิเวศ" }] },
    { word: "biodiversity", pos: "n.", thai: "ความหลากหลายทางชีวภาพ", definition: "variety of life", hint: "life variety", cats: ["nature"], examples: [{ en: "Biodiversity is decreasing.", th: "ความหลากหลายทางชีวภาพลดลง" }] },
    { word: "sustainability", pos: "n.", thai: "ความยั่งยืน", definition: "ability to maintain", hint: "long-term maintenance", cats: ["nature"], examples: [{ en: "Focus on sustainability.", th: "มุ่งเน้นความยั่งยืน" }] },
    { word: "renewable", pos: "adj.", thai: "หมุนเวียนได้", definition: "can be replenished", hint: "reusable", cats: ["nature"], examples: [{ en: "Solar energy is renewable.", th: "พลังงานแสงอาทิตย์หมุนเวียนได้" }] },
    { word: "fossil", pos: "n.", thai: "ฟอสซิล", definition: "remains of ancient life", hint: "ancient remains", cats: ["nature"], examples: [{ en: "Fossil fuels cause pollution.", th: "เชื้อเพลิงฟอสซิลทำให้เกิดมลพิษ" }] },
    { word: "carbon", pos: "n.", thai: "คาร์บอน", definition: "chemical element", hint: "chemical element", cats: ["nature"], examples: [{ en: "Reduce carbon emissions.", th: "ลดการปล่อยคาร์บอน" }] },

    // Culture & Society (30 words)
    { word: "culture", pos: "n.", thai: "วัฒนธรรม", definition: "way of life of people", hint: "traditions customs", cats: ["social"], examples: [{ en: "Thai culture is rich.", th: "วัฒนธรรมไทยมีความหลากหลาย" }] },
    { word: "tradition", pos: "n.", thai: "ประเพณี", definition: "customs passed down", hint: "old customs", cats: ["social"], examples: [{ en: "We follow family traditions.", th: "เราปฏิบัติตามประเพณีครอบครัว" }] },
    { word: "ceremony", pos: "n.", thai: "พิธีการ", definition: "formal religious or public occasion", hint: "formal event", cats: ["social"], examples: [{ en: "The wedding ceremony was beautiful.", th: "พิธีแต่งงานสวยงาม" }] },
    { word: "festival", pos: "n.", thai: "เทศกาล", definition: "celebration event", hint: "celebration time", cats: ["social"], examples: [{ en: "The music festival was amazing.", th: "เทศกาลดนตรีน่าทึ่ง" }] },
    { word: "heritage", pos: "n.", thai: "มรดก", definition: "things inherited from past", hint: "cultural legacy", cats: ["social"], examples: [{ en: "Preserve cultural heritage.", th: "อนุรักษ์มรดกทางวัฒนธรรม" }] },
    { word: "diversity", pos: "n.", thai: "ความหลากหลาย", definition: "variety of different things", hint: "variety", cats: ["social"], examples: [{ en: "Celebrate cultural diversity.", th: "เฉลิมฉลองความหลากหลายทางวัฒนธรรม" }] },
    { word: "identity", pos: "n.", thai: "เอกลักษณ์", definition: "characteristics that define", hint: "defining features", cats: ["social"], examples: [{ en: "National identity is important.", th: "เอกลักษณ์ชาติสำคัญ" }] },
    { word: "ethnicity", pos: "n.", thai: "เชื้อชาติ", definition: "cultural group identity", hint: "cultural group", cats: ["social"], examples: [{ en: "Respect all ethnicities.", th: "เคารพทุกเชื้อชาติ" }] },
    { word: "minority", pos: "n.", thai: "ชนกลุ่มน้อย", definition: "smaller group in population", hint: "smaller group", cats: ["social"], examples: [{ en: "Protect minority rights.", th: "ปกป้องสิทธิชนกลุ่มน้อย" }] },
    { word: "majority", pos: "n.", thai: "ชนกลุ่มใหญ่", definition: "larger group in population", hint: "larger group", cats: ["social"], examples: [{ en: "The majority voted yes.", th: "ชนกลุ่มใหญ่โหวตเห็นด้วย" }] },
    { word: "integration", pos: "n.", thai: "การรวมเข้าด้วยกัน", definition: "combining into whole", hint: "joining together", cats: ["social"], examples: [{ en: "Social integration takes time.", th: "การรวมเข้าสังคมใช้เวลา" }] },
    { word: "assimilation", pos: "n.", thai: "การกลมกลืน", definition: "becoming part of group", hint: "blending in", cats: ["social"], examples: [{ en: "Cultural assimilation is complex.", th: "การกลมกลืนทางวัฒนธรรมซับซ้อน" }] },
    { word: "discrimination", pos: "n.", thai: "การเลือกปฏิบัติ", definition: "unfair treatment", hint: "unfair treatment", cats: ["social"], examples: [{ en: "Fight against discrimination.", th: "ต่อสู้กับการเลือกปฏิบัติ" }] },
    { word: "prejudice", pos: "n.", thai: "อคติ", definition: "unfair opinion", hint: "biased opinion", cats: ["social"], examples: [{ en: "Overcome prejudice with education.", th: "เอาชนะอคติด้วยการศึกษา" }] },
    { word: "stereotype", pos: "n.", thai: "แบบแผนตายตัว", definition: "oversimplified image", hint: "fixed image", cats: ["social"], examples: [{ en: "Don't believe stereotypes.", th: "อย่าเชื่อแบบแผนตายตัว" }] },
    { word: "tolerance", pos: "n.", thai: "ความอดทน", definition: "accepting differences", hint: "accepting others", cats: ["social"], examples: [{ en: "Practice religious tolerance.", th: "ปฏิบัติความอดทนทางศาสนา" }] },
    { word: "acceptance", pos: "n.", thai: "การยอมรับ", definition: "willingness to accept", hint: "willing to accept", cats: ["social"], examples: [{ en: "Social acceptance is important.", th: "การยอมรับทางสังคมสำคัญ" }] },
    { word: "inclusion", pos: "n.", thai: "การรวมเข้าด้วยกัน", definition: "including everyone", hint: "including all", cats: ["social"], examples: [{ en: "Promote social inclusion.", th: "ส่งเสริมการรวมเข้าสังคม" }] },
    { word: "exclusion", pos: "n.", thai: "การแยกออก", definition: "keeping someone out", hint: "leaving out", cats: ["social"], examples: [{ en: "Social exclusion causes problems.", th: "การแยกออกจากสังคมสร้างปัญหา" }] },
    { word: "equality", pos: "n.", thai: "ความเท่าเทียม", definition: "being equal", hint: "same treatment", cats: ["social"], examples: [{ en: "Fight for gender equality.", th: "ต่อสู้เพื่อความเท่าเทียมทางเพศ" }] },
    { word: "inequality", pos: "n.", thai: "ความไม่เท่าเทียม", definition: "unfair differences", hint: "unfair differences", cats: ["social"], examples: [{ en: "Income inequality is growing.", th: "ความไม่เท่าเทียมรายได้เพิ่มขึ้น" }] },
    { word: "justice", pos: "n.", thai: "ความยุติธรรม", definition: "fair treatment", hint: "fairness", cats: ["social"], examples: [{ en: "Seek justice for all.", th: "แสวงหาความยุติธรรมสำหรับทุกคน" }] },
    { word: "injustice", pos: "n.", thai: "ความไม่ยุติธรรม", definition: "unfair treatment", hint: "unfairness", cats: ["social"], examples: [{ en: "Fight against injustice.", th: "ต่อสู้กับความไม่ยุติธรรม" }] },
    { word: "oppression", pos: "n.", thai: "การกดขี่", definition: "harsh treatment", hint: "harsh control", cats: ["social"], examples: [{ en: "End oppression of minorities.", th: "ยุติการกดขี่ชนกลุ่มน้อย" }] },
    { word: "liberation", pos: "n.", thai: "การปลดปล่อย", definition: "freedom from oppression", hint: "gaining freedom", cats: ["social"], examples: [{ en: "Liberation requires struggle.", th: "การปลดปล่อยต้องใช้การต่อสู้" }] },
    { word: "empowerment", pos: "n.", thai: "การเสริมสร้างพลัง", definition: "giving power to", hint: "giving strength", cats: ["social"], examples: [{ en: "Women's empowerment is crucial.", th: "การเสริมสร้างพลังสตรีสำคัญ" }] },
    { word: "activism", pos: "n.", thai: "การเคลื่อนไหวเพื่อสังคม", definition: "working for social change", hint: "social action", cats: ["social"], examples: [{ en: "Environmental activism grows.", th: "การเคลื่อนไหวด้านสิ่งแวดล้อมเติบโต" }] },
    { word: "advocacy", pos: "n.", thai: "การสนับสนุน", definition: "supporting a cause", hint: "supporting cause", cats: ["social"], examples: [{ en: "Human rights advocacy is important.", th: "การสนับสนุนสิทธิมนุษยชนสำคัญ" }] },
    { word: "reform", pos: "n.", thai: "การปฏิรูป", definition: "improvement of system", hint: "system improvement", cats: ["social"], examples: [{ en: "Education reform is needed.", th: "การปฏิรูปการศึกษาจำเป็น" }] },
    { word: "revolution", pos: "n.", thai: "การปฏิวัติ", definition: "complete change", hint: "total change", cats: ["social"], examples: [{ en: "The industrial revolution changed society.", th: "การปฏิวัติอุตสาหกรรมเปลี่ยนสังคม" }] },

    // Politics & Government (30 words)
    { word: "government", pos: "n.", thai: "รัฐบาล", definition: "system that rules country", hint: "political system", cats: ["social"], examples: [{ en: "The government makes laws.", th: "รัฐบาลสร้างกฎหมาย" }] },
    { word: "democracy", pos: "n.", thai: "ประชาธิปไตย", definition: "government by the people", hint: "people power", cats: ["social"], examples: [{ en: "Democracy gives people voice.", th: "ประชาธิปไตยให้เสียงประชาชน" }] },
    { word: "election", pos: "n.", thai: "การเลือกตั้ง", definition: "choosing leaders by voting", hint: "voting process", cats: ["social"], examples: [{ en: "Elections are held every four years.", th: "การเลือกตั้งจัดทุกสี่ปี" }] },
    { word: "candidate", pos: "n.", thai: "ผู้สมัคร", definition: "person running for office", hint: "election runner", cats: ["social"], examples: [{ en: "The candidate gave a speech.", th: "ผู้สมัครกล่าวสุนทรพจน์" }] },
    { word: "campaign", pos: "n.", thai: "การหาเสียง", definition: "activities to win election", hint: "election activities", cats: ["social"], examples: [{ en: "The campaign was successful.", th: "การหาเสียงสำเร็จ" }] },
    { word: "vote", pos: "v.", thai: "ลงคะแนน", definition: "choose by ballot", hint: "choose candidate", cats: ["social"], examples: [{ en: "Citizens vote for leaders.", th: "ประชาชนลงคะแนนเลือกผู้นำ" }] },
    { word: "ballot", pos: "n.", thai: "บัตรลงคะแนน", definition: "paper for voting", hint: "voting paper", cats: ["social"], examples: [{ en: "Mark your ballot carefully.", th: "ทำเครื่องหมายบัตรลงคะแนนอย่างระมัดระวัง" }] },
    { word: "parliament", pos: "n.", thai: "รัฐสภา", definition: "legislative body", hint: "law-making body", cats: ["social"], examples: [{ en: "Parliament passed the law.", th: "รัฐสภาผ่านกฎหมาย" }] },
    { word: "congress", pos: "n.", thai: "สภาคองเกรส", definition: "legislative assembly", hint: "law assembly", cats: ["social"], examples: [{ en: "Congress debates new laws.", th: "สภาคองเกรสอภิปรายกฎหมายใหม่" }] },
    { word: "senate", pos: "n.", thai: "วุฒิสภา", definition: "upper house of legislature", hint: "upper house", cats: ["social"], examples: [{ en: "The senate approved the bill.", th: "วุฒิสภาอนุมัติร่างกฎหมาย" }] },
    { word: "legislation", pos: "n.", thai: "การออกกฎหมาย", definition: "making laws", hint: "law making", cats: ["social"], examples: [{ en: "New legislation protects workers.", th: "กฎหมายใหม่ปกป้องคนงาน" }] },
    { word: "policy", pos: "n.", thai: "นโยบาย", definition: "course of action", hint: "action plan", cats: ["social"], examples: [{ en: "The policy helps families.", th: "นโยบายช่วยครอบครัว" }] },
    { word: "constitution", pos: "n.", thai: "รัฐธรรมนูญ", definition: "fundamental law", hint: "basic law", cats: ["social"], examples: [{ en: "The constitution protects rights.", th: "รัฐธรรมนูญปกป้องสิทธิ" }] },
    { word: "amendment", pos: "n.", thai: "การแก้ไขเพิ่มเติม", definition: "change to constitution", hint: "law change", cats: ["social"], examples: [{ en: "The amendment was ratified.", th: "การแก้ไขเพิ่มเติมได้รับการอนุมัติ" }] },
    { word: "republic", pos: "n.", thai: "สาธารณรัฐ", definition: "state with elected leaders", hint: "elected government", cats: ["social"], examples: [{ en: "France is a republic.", th: "ฝรั่งเศสเป็นสาธารณรัฐ" }] },
    { word: "monarchy", pos: "n.", thai: "ระบอบกษัตริย์", definition: "rule by king or queen", hint: "royal rule", cats: ["social"], examples: [{ en: "Thailand is a constitutional monarchy.", th: "ไทยเป็นระบอบกษัตริย์ภายใต้รัฐธรรมนูญ" }] },
    { word: "dictatorship", pos: "n.", thai: "เผด็จการ", definition: "rule by one person", hint: "one-person rule", cats: ["social"], examples: [{ en: "Dictatorship limits freedom.", th: "เผด็จการจำกัดเสรีภาพ" }] },
    { word: "authority", pos: "n.", thai: "อำนาจ", definition: "power to control", hint: "control power", cats: ["social"], examples: [{ en: "Government has authority.", th: "รัฐบาลมีอำนาจ" }] },
    { word: "sovereignty", pos: "n.", thai: "อำนาจอธิปไตย", definition: "supreme power", hint: "highest power", cats: ["social"], examples: [{ en: "National sovereignty is important.", th: "อำนาจอธิปไตยของชาติสำคัญ" }] },
    { word: "citizenship", pos: "n.", thai: "สัญชาติ", definition: "membership in country", hint: "country membership", cats: ["social"], examples: [{ en: "Citizenship brings rights and duties.", th: "สัญชาติให้สิทธิและหน้าที่" }] },
    { word: "patriotism", pos: "n.", thai: "ความรักชาติ", definition: "love for one's country", hint: "country love", cats: ["social"], examples: [{ en: "Patriotism inspires service.", th: "ความรักชาติสร้างแรงบันดาลใจในการรับใช้" }] },
    { word: "nationalism", pos: "n.", thai: "ลัทธิชาตินิยม", definition: "strong national identity", hint: "strong national pride", cats: ["social"], examples: [{ en: "Nationalism can unite or divide.", th: "ลัทธิชาตินิยมสามารถรวมหรือแบ่งแยก" }] },
    { word: "ideology", pos: "n.", thai: "อุดมการณ์", definition: "system of ideas", hint: "belief system", cats: ["social"], examples: [{ en: "Political ideology shapes policy.", th: "อุดมการณ์ทางการเมืองกำหนดนโยบาย" }] },
    { word: "propaganda", pos: "n.", thai: "การโฆษณาชวนเชื่อ", definition: "biased information", hint: "biased promotion", cats: ["social"], examples: [{ en: "Propaganda influences opinions.", th: "การโฆษณาชวนเชื่อมีอิทธิพลต่อความคิดเห็น" }] },
    { word: "corruption", pos: "n.", thai: "การทุจริต", definition: "dishonest conduct", hint: "dishonest behavior", cats: ["social"], examples: [{ en: "Fight against corruption.", th: "ต่อสู้กับการทุจริต" }] },
    { word: "transparency", pos: "n.", thai: "ความโปร่งใส", definition: "openness in government", hint: "open government", cats: ["social"], examples: [{ en: "Transparency builds trust.", th: "ความโปร่งใสสร้างความไว้วางใจ" }] },
    { word: "accountability", pos: "n.", thai: "ความรับผิดชอบ", definition: "being responsible", hint: "taking responsibility", cats: ["social"], examples: [{ en: "Leaders need accountability.", th: "ผู้นำต้องมีความรับผิดชอบ" }] },
    { word: "bureaucracy", pos: "n.", thai: "ระบบราชการ", definition: "government administration", hint: "government system", cats: ["social"], examples: [{ en: "Bureaucracy can be slow.", th: "ระบบราชการอาจช้า" }] },
    { word: "diplomacy", pos: "n.", thai: "การทูต", definition: "international relations", hint: "country relations", cats: ["social"], examples: [{ en: "Diplomacy prevents war.", th: "การทูตป้องกันสงคราม" }] },
    { word: "treaty", pos: "n.", thai: "สนธิสัญญา", definition: "agreement between countries", hint: "country agreement", cats: ["social"], examples: [{ en: "The treaty promotes peace.", th: "สนธิสัญญาส่งเสริมสันติภาพ" }] },

    // Psychology & Human Behavior (30 words)
    { word: "psychology", pos: "n.", thai: "จิตวิทยา", definition: "study of mind and behavior", hint: "mind study", cats: ["school"], examples: [{ en: "Psychology explains behavior.", th: "จิตวิทยาอธิบายพฤติกรรม" }] },
    { word: "behavior", pos: "n.", thai: "พฤติกรรม", definition: "way of acting", hint: "actions", cats: ["social"], examples: [{ en: "Good behavior is important.", th: "พฤติกรรมดีสำคัญ" }] },
    { word: "personality", pos: "n.", thai: "บุคลิกภาพ", definition: "individual character", hint: "character traits", cats: ["social"], examples: [{ en: "She has a friendly personality.", th: "เธอมีบุคลิกภาพเป็นมิตร" }] },
    { word: "emotion", pos: "n.", thai: "อารมณ์", definition: "feeling state", hint: "feelings", cats: ["social"], examples: [{ en: "Control your emotions.", th: "ควบคุมอารมณ์ของคุณ" }] },
    { word: "motivation", pos: "n.", thai: "แรงจูงใจ", definition: "reason for action", hint: "driving force", cats: ["social"], examples: [{ en: "Find your motivation.", th: "หาแรงจูงใจของคุณ" }] },
    { word: "attitude", pos: "n.", thai: "ทัศนคติ", definition: "way of thinking", hint: "mindset", cats: ["social"], examples: [{ en: "Positive attitude helps success.", th: "ทัศนคติเชิงบวกช่วยความสำเร็จ" }] },
    { word: "perception", pos: "n.", thai: "การรับรู้", definition: "way of understanding", hint: "understanding", cats: ["social"], examples: [{ en: "Perception affects judgment.", th: "การรับรู้ส่งผลต่อการตัดสิน" }] },
    { word: "consciousness", pos: "n.", thai: "สติสัมปชัญญะ", definition: "awareness of surroundings", hint: "awareness", cats: ["social"], examples: [{ en: "Consciousness is complex.", th: "สติสัมปชัญญะซับซ้อน" }] },
    { word: "subconscious", pos: "adj.", thai: "จิตใต้สำนึก", definition: "below conscious awareness", hint: "hidden mind", cats: ["social"], examples: [{ en: "Subconscious influences behavior.", th: "จิตใต้สำนึกมีอิทธิพลต่อพฤติกรรม" }] },
    { word: "instinct", pos: "n.", thai: "สัญชาตญาณ", definition: "natural behavior", hint: "natural response", cats: ["social"], examples: [{ en: "Trust your instinct.", th: "เชื่อสัญชาตญาณของคุณ" }] },
    { word: "intuition", pos: "n.", thai: "ลางสังหรณ์", definition: "immediate understanding", hint: "gut feeling", cats: ["social"], examples: [{ en: "Her intuition was correct.", th: "ลางสังหรณ์ของเธอถูกต้อง" }] },
    { word: "intelligence", pos: "n.", thai: "สติปัญญา", definition: "ability to learn", hint: "learning ability", cats: ["social"], examples: [{ en: "Intelligence comes in many forms.", th: "สติปัญญามีหลายรูปแบบ" }] },
    { word: "creativity", pos: "n.", thai: "ความคิดสร้างสรรค์", definition: "ability to create", hint: "creative ability", cats: ["social"], examples: [{ en: "Creativity solves problems.", th: "ความคิดสร้างสรรค์แก้ปัญหา" }] },
    { word: "memory", pos: "n.", thai: "ความจำ", definition: "ability to remember", hint: "remembering", cats: ["social"], examples: [{ en: "Memory fades with age.", th: "ความจำลดลงตามอายุ" }] },
    { word: "learning", pos: "n.", thai: "การเรียนรู้", definition: "acquiring knowledge", hint: "gaining knowledge", cats: ["school"], examples: [{ en: "Learning never stops.", th: "การเรียนรู้ไม่มีวันหยุด" }] },
    { word: "adaptation", pos: "n.", thai: "การปรับตัว", definition: "adjusting to change", hint: "adjusting", cats: ["social"], examples: [{ en: "Adaptation is survival.", th: "การปรับตัวคือการอยู่รอด" }] },
    { word: "resilience", pos: "n.", thai: "ความยืดหยุ่น", definition: "ability to recover", hint: "bouncing back", cats: ["social"], examples: [{ en: "Build resilience through challenges.", th: "สร้างความยืดหยุ่นผ่านความท้าทาย" }] },
    { word: "anxiety", pos: "n.", thai: "ความวิตกกังวล", definition: "feeling of worry", hint: "worry feeling", cats: ["health"], examples: [{ en: "Anxiety affects performance.", th: "ความวิตกกังวลส่งผลต่อผลงาน" }] },
    { word: "depression", pos: "n.", thai: "ภาวะซึมเศร้า", definition: "persistent sadness", hint: "deep sadness", cats: ["health"], examples: [{ en: "Depression needs treatment.", th: "ภาวะซึมเศร้าต้องรักษา" }] },
    { word: "confidence", pos: "n.", thai: "ความมั่นใจ", definition: "belief in oneself", hint: "self-belief", cats: ["social"], examples: [{ en: "Confidence improves performance.", th: "ความมั่นใจเพิ่มผลงาน" }] },
    { word: "self-esteem", pos: "n.", thai: "การเห็นคุณค่าในตนเอง", definition: "respect for oneself", hint: "self-respect", cats: ["social"], examples: [{ en: "Build healthy self-esteem.", th: "สร้างการเห็นคุณค่าในตนเองที่ดี" }] },
    { word: "empathy", pos: "n.", thai: "ความเห็นอกเห็นใจ", definition: "understanding others' feelings", hint: "feeling for others", cats: ["social"], examples: [{ en: "Empathy builds relationships.", th: "ความเห็นอกเห็นใจสร้างความสัมพันธ์" }] },
    { word: "sympathy", pos: "n.", thai: "ความเห็นใจ", definition: "feeling sorry for others", hint: "feeling sorry", cats: ["social"], examples: [{ en: "Show sympathy to those in need.", th: "แสดงความเห็นใจต่อผู้ที่ต้องการ" }] },
    { word: "compassion", pos: "n.", thai: "ความเมตตา", definition: "caring concern for others", hint: "caring for others", cats: ["social"], examples: [{ en: "Compassion heals wounds.", th: "ความเมตตารักษาบาดแผล" }] },
    { word: "prejudice", pos: "n.", thai: "อคติ", definition: "unfair judgment", hint: "biased opinion", cats: ["social"], examples: [{ en: "Overcome prejudice with understanding.", th: "เอาชนะอคติด้วยความเข้าใจ" }] },
    { word: "stereotype", pos: "n.", thai: "แบบแผนตายตัว", definition: "oversimplified belief", hint: "fixed belief", cats: ["social"], examples: [{ en: "Challenge harmful stereotypes.", th: "ท้าทายแบบแผนตายตัวที่เป็นอันตราย" }] },
    { word: "bias", pos: "n.", thai: "ความลำเอียง", definition: "unfair preference", hint: "unfair leaning", cats: ["social"], examples: [{ en: "Recognize your own bias.", th: "รู้จักความลำเอียงของตนเอง" }] },
    { word: "manipulation", pos: "n.", thai: "การจัดการ", definition: "controlling others unfairly", hint: "unfair control", cats: ["social"], examples: [{ en: "Avoid manipulation tactics.", th: "หลีกเลี่ยงกลยุทธ์การจัดการ" }] },
    { word: "influence", pos: "n.", thai: "อิทธิพล", definition: "power to affect others", hint: "affecting power", cats: ["social"], examples: [{ en: "Use your influence wisely.", th: "ใช้อิทธิพลของคุณอย่างฉลาด" }] },
    { word: "persuasion", pos: "n.", thai: "การชักจูง", definition: "convincing others", hint: "convincing", cats: ["social"], examples: [{ en: "Persuasion requires skill.", th: "การชักจูงต้องใช้ทักษะ" }] }
];

console.log(`B2 words prepared: ${b2Words.length}/150`);

// Add words to vocabulary
async function addB2Words() {
    console.log('Adding B2 level words...');
    for (const word of b2Words) {
        await vm.addWord(word.word, word.pos, word.thai, word.definition, word.hint, word.cats, word.examples, 'B2');
    }
    console.log(`Added ${b2Words.length} B2 words successfully!`);
}

// Run if called directly
if (require.main === module) {
    addB2Words().catch(console.error);
}

module.exports = { b2Words, addB2Words };